# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
dataset: ag-vampir-002
panel: ag-vampir
metadata: config/metadata_ms.tsv
cohort-columns:
  - location
  - taxon
targets: config/ag-vampir.bed


# Directory of Illumina Miseq Run
illumina-dir: resources/14_02_2024_MiSeq_output/

# Specify whether reference  provided is amplicon or wholegenome sequence data
# Genome fasta reference files
reference-name: AgamP4
reference-fasta: resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa
reference-gff3: resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3
reference-snpeffdb: Anopheles_gambiae

# Specify whether to convert bcl files to fastq
# or whether we provide fastq data in the metadata / or auto naming 
bcl-convert: True
fastq:
  auto: True

# Specify whether to run quality-control analyses
quality-control:
  sample-total-reads-threshold: 250
  amplicon-total-reads-threshold: 1000

  fastp: True
  coverage: True
  qualimap: False
  stats: True
  multiqc: True

# Specify whether to run generic analyses
analysis:  
  igv: True
  sample-map: False # needs lat and longs
  pca: True
  genetic-diversity: True
  allele-frequencies: True

# Specify whether to build jupyter results book
build-jupyter-book: True
