# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
dataset: lab-strains
panel: ag-vampir
cohort-columns:
  - location
  - taxon
  - country
targets: config/ag-vampir.bed
metadata: blah

# Directory of Illumina Miseq Run, can be empty 
illumina-dir: resources/250110_M05658_0028_000000000-LTBV4

# Specify whether reference  provided is amplicon or wholegenome sequence data
# Genome fasta reference files
reference-fasta: resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa
reference-gff3: resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3
reference-snpeffdb: Anopheles_gambiae
custom-snpeffdb: False

# Specify whether to convert bcl files to fastq
# or whether we provide fastq data in the metadata / or auto naming 
from-bcl: True
fastq:
  auto: True

# Specify whether to run quality-control analyses
quality-control:
  sample-total-reads-threshold: 250
  amplicon-total-reads-threshold: 1000

  fastp: True
  coverage: True
  stats: True
  multiqc: True

# Specify whether to run generic analyses
analysis:  
  sample-map: False # needs lat and longs
  population-structure: True
  genetic-diversity: True
  allele-frequencies: True

# Specify whether to build jupyter results book
build-jupyter-book: True
