# Dataset main configurations
dataset: wassun
panel: aaegis
cohort-columns:
  - location
  - taxon
  - country

# If amplicons have multiple markers of interest then set these inputs accordingly
# If there is one marker of interest per amplicon then the targets and amplicons files can be the same
targets: config/aaegis_targets.bed
amplicons: config/aaegis_amplicons.bed
metadata: config/aaegis_run_metadata.tsv

# Specify whether any 
multi-target-amplicons: True 
amplicons: config/aaegis_amplicons.bed

from-bcl: True
# Directory of Illumina Miseq Run, can be empty 
illumina-dir: resources/250110_M05658_0028_000000000-LTBV4

# Genome fasta reference files
reference-fasta: resources/reference/VectorBase-68_AaegyptiLVP_AGWG_Genome.fasta
reference-gff3: resources/reference/VectorBase-68_AaegyptiLVP_AGWG.gff
reference-snpeffdb: Aedes_aegypti_lvpagwg
custom-snpeffdb: True # Set as true as Aaeg chromosomes differ in snpeff database

# Specify whether to run quality-control analyses
quality-control:
  sample-total-reads-threshold: 250
  amplicon-total-reads-threshold: 100

  coverage: True
  stats: True
  multiqc: True

# Specify whether to run generic analyses
analysis:  
  sample-map: False # needs lat and longs
  population-structure: True
  genetic-diversity: True
  allele-frequencies: True

# Specify whether to build jupyter results book
build-jupyter-book: True
