# Dataset main configurations
dataset: lab-strains
panel: ag-vampir
cohort-columns:
  - location
  - taxon
  - country
targets: config/ag-vampir.bed
metadata: ""

from-bcl: True
# Directory of Illumina Miseq Run, can be empty 
illumina-dir: resources/250110_M05658_0028_000000000-LTBV4

# Genome fasta reference files
reference-fasta: resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa
reference-gff3: resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3
reference-snpeffdb: Anopheles_gambiae
custom-snpeffdb: False

# Specify whether to run quality-control analyses
quality-control:
  sample-total-reads-threshold: 250
  amplicon-total-reads-threshold: 1000

  coverage: True
  stats: True
  multiqc: True

# Specify whether to run generic analyses
analysis:  
  sample-map: False # needs lat and longs
  population-structure: True
  genetic-diversity: True
  allele-frequencies: True

# Specify whether to build jupyter results book
build-jupyter-book: True
