name: AmpSeeker-ag-vampir

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  run-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - name: Set up python3
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}


      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test workflow 
        uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache --configfile .test/config/config_agvampir.yaml'
          stagein: 
            "
            pip install scikit-allel numba pandas &&
            wget https://vectorbase.org/common/downloads/release-66/AgambiaePEST/fasta/data/VectorBase-66_AgambiaePEST_Genome.fasta -q -O - | sed 's/AgamP4_//g' > .test/resources/reference/AgamP4.fa &&
            cp config/ag-vampir.bed .test/config/ag-vampir.bed &&
            cp resources/*npy resources/*csv resources/*pickle .test/resources/. &&
            cp -r docs/ .test/docs/ &&
            conda config --set channel_priority flexible &&
            mkdir -pv .test/workflow && 
            cp workflow/ampseekertools.py .test/workflow/
            "